session_name: IDE
windows:
  - window_name: IDE
    layout: main-vertical
    options:
      main-pane-width: 25%
    panes:
      - shell_command:
          - cd ~/Documents/Notes/Projects/IDE
          # - nvim Notes.md ToDo.md
          - open-project
      - shell_command:
          - tmux resizep -y 90%
          #- sleep 0.1
          - nvim
        focus: true
      - clear
